### ISSUE TITLE
problem to assign permissions to a group of directories

### ISSUE THREAD

**Issue by lorsistem** [sjarvela/mollify#8]
hello! Good Afternoon happen to have another drawback.

it is the area of ​​permits, I will try to explain as best you can and see if you can help

6 users have created (U1, U2, U3, U4, U5, U6) which each have permissions assigned by default but those 6 users add them to a group called (CALID-UGD) options
permissions for that group are read-write-erase
 
moreover I have a number of directories and sub-directories

Human Resources
  -
  -
IT
  -
  -
  -
Operations
 -
 -
 -
Security
 -
 -
 -

 Organized by departments, so for a particular folder in this case "Operations" give access to the group (CALID-UGD) is in this group where I want those 6 users have access read-write-erase
any folder or file found under the root "Operations". but yet not in the other folders (HR, IT, Security) where I just want to have access to reading.

I tried to make all those settings that you tell no success.

When I try through the option to assign privileges element permits the group to the root directory I guess I should assign to all subdirectories contained within that root
but yet I notice that the configuration is only assigned to the first folder, ie I have to go accessing folder by folder and file by file and go assigning individual permissions
each, this is tedious and also if my users are not administrators when adding a new file will not be able to assign the permisologia so it can not be deleted or edited by another that does not belong to the group
then always should contact the administrator to assign permissions, my serious question how we could give you the option to assign permissions to users in that group without them being
administrators file manager? do you get me ??

I welcome your comments, greetings from a girl from Venezuela, I apologize for my bad English;)

Grateful for your help.

**Comment by sjarvela** [comment]
You should put system default permission to read-only, this way users can only read unless defined otherwise.

Then if users are part of groups, then you assign group permissions to the root folders.

Permissions are inherited, so you need to only assign one permission for group&root folder.

If you are uncertain why user has/does not have some permission, with admin you can open "Permissions..." from file/folder context menu, and then choose "User Permissions". There you can inspect any user that what permissions are set and where (and what is the effective permission).

**Comment by sjarvela** [comment]
Closing as there seems to be no progress. Anyway, further discussion should be continued at https://github.com/sjarvela/kloudspeaker/
