### ISSUE TITLE
History plugin: Support for move operation

### ISSUE THREAD

**Issue by sjarvela** [sjarvela/mollify#9]
In history plugin, it should be possible to enable versioning when file is moved over existing.

What makes this different than versioning with copy, in move the original copy and all its metadata (comments, descriptions, permissions) and history of its own would be lost when the file is merged into the target.

**Comment by luke7263** [comment]
About History plugin and new options:

- store_current_on_restore: works fine
- version_on_copy: works fine
- version_on_move: works fine

The drop-type parameter values "move" and "copy" work fine too.
Restore of any version works fine.

But pb when viewing a versionned txt file when clicking on the tiny eye icon (kloudspeaker 2.6.7.1 rev 19), the popup is displayed but empty (I may have a obsolete version since the TextFile.viewer.php date is 2010 May 1st):

PHP Fatal error:  Call to a member function extension() on a non-object in /web/cloudfiles.fr/backend/plugin/FileViewerEditor/viewers/TextFile/TextFile.viewer.php on line 56

By the way, I remember viewing a versionned txt file has never worked. In my current official site (mollify 2.6.7 rev 19), I have these errors:

MOLLIFY ERROR: ServiceException: INVALID_REQUEST=Invalid HistoryServices request: POST history/items/55223a9ac86a4/25D4D466C0D246FB81AF1562E527C8AC/details, referer: http://cloudfiles.fr/connect.php?v=files/54a7fb15b4e43
MOLLIFY ERROR: {0:{file:/web/cloudfiles.fr/backend/plugin/History/HistoryServices.class.php, line:64, function:invalidRequestException, class:ServicesBase, type:->, args:{}}, 1:{file:/web/cloudfiles.fr/backend/include/services/ServicesBase.class.php, line:59, function:processPost, class:HistoryServices, type:->, args:{}}, 2:{file:/web/cloudfiles.fr/backend/include/MollifyBackend.class.php, line:85, function:processRequest, class:ServicesBase, type:->, args:{}}, 3:{file:/web/cloudfiles.fr/backend/r.php, line:81, function:processRequest, class:MollifyBackend, type:->, args:{0:Request}}}, referer: http://cloudfiles.fr/connect.php?v=files/54a7fb15b4e43

**Comment by sjarvela** [comment]
Text file viewer is indeed from 2010. It tried to access the item locally (text is read and output directly to the page, other viewers don't do it like this), which does not work with history. I've now added support for accessing content from viewers, will be in next release.

**Comment by sjarvela** [comment]
Text file viewer 1.1 released with 2.6.8.
